AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - '.pryrc'

Rails:
  Enabled: true

FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false
