version: '2'
services:
  db:
    image: 'postgres:12-alpine'
    volumes:
      - 'my_bank_db:/var/lib/postgresql/data'
    restart: always
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    volumes:
      - 'my_bank_redis:/data'
    restart: always
  app: &app_base
    image: 'ardation/my_bank:latest'
    build:
      context: .
      args:
        - FOLDERS_TO_REMOVE=spec node_modules vendor/assets lib/assets tmp/cache
        - BUNDLE_WITHOUT=development:test
        - RAILS_ENV=production
    environment:
      - DB_HOST=db
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
    links:
      - db
      - redis
    restart: always
    ports:
      - '3000:3000'
  worker:
    <<: *app_base
    command: bundle exec sidekiq
    ports: []
volumes:
  my_bank_redis:
  my_bank_db:
