version: '2.4'
services:
  postgres:
    image: 'postgres:12-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    restart: always
  app: &app_base
    image: my_bank
    build:
      context: .
      args:
        - FOLDERS_TO_REMOVE=spec node_modules vendor/assets lib/assets tmp/cache
        - BUNDLE_WITHOUT=development:test
        - RAILS_ENV=production
    links:
      - postgres
      - redis
    ports:
      - 3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000 || exit 1"]
      interval: 5m
      start_period: 1m
  worker:
    <<: *app_base
    command: bundle exec sidekiq
    healthcheck:
      test: "ps ax | grep -v grep | grep sidekiq"
      interval: 1m
      start_period: 1m
volumes:
  redis:
  postgres:
