bank_sync_collection_worker:
  cron: "*/10 * * * *"
  class: "Bank::SyncCollectionWorker"
  queue: cron
integration_sync_collection_worker:
  cron: "5-59/10 * * * *"
  class: "Integration::SyncCollectionWorker"
  queue: cron
