bank_sync_collection_job:
  cron: "*/10 * * * *"
  class: "Bank::SyncCollectionJob"
  queue: cron
integration_sync_collection_job:
  cron: "0 0 */1 * *"
  class: "Integration::SyncCollectionJob"
  queue: cron
