bank_sync_collection_worker:
  cron: "*/10 * * * *"
  class: "Bank::SyncCollectionWorker"
  queue: cron
integration_sync_collection_worker:
  cron: "0 0 */1 * *"
  class: "Integration::SyncCollectionWorker"
  queue: cron
